### ISSUE TITLE
Pod install problem

### ISSUE THREAD

**Issue by VictorLiubchenko** [matrix-org/matrix-ios-kit#188] opened 2016-11-10 15:07 UTC
When run pod install get error like in this issue.  https://github.com/OliverLetterer/GHMarkdownParser/issues/12

with GHMarkdownParser dependency.

**Comment by giomfo** [comment] 2017-01-06 09:24
Cannot be reproduced.

@VictorLiubchenko do you still observe this error?

**Comment by olumby** [comment] 2017-01-12 13:05
I think @VictorLiubchenko is trying to build on Swift.

The full log:

```
/Path/Pods/GHMarkdownParser/discount/mkdio.h:6:14: Typedef redefinition with different types ('void' vs 'struct mmiot')
/Path/Pods/GHMarkdownParser/discount/mkdio.h:12:8: Conflicting types for 'mkd_in'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:13:8: Conflicting types for 'mkd_string'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:17:8: Conflicting types for 'gfm_in'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:18:8: Conflicting types for 'gfm_string'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:20:6: Conflicting types for 'mkd_basename'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:28:5: Conflicting types for 'mkd_compile'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:29:6: Conflicting types for 'mkd_cleanup'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:48:5: Conflicting types for 'mkd_document'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:50:5: Conflicting types for 'mkd_css'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:55:5: Conflicting types for 'mkd_generatehtml'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:58:5: Conflicting types for 'mkd_generatecss'
/Path/Pods/GHMarkdownParser/discount/mkdio.h:79:6: Conflicting types for 'mkd_ref_prefix'
```
```
/Path/Pods/MatrixKit/MatrixKit/Utils/MXKEventFormatter.m:25:9: Could not build module 'GHMarkdownParser'
```

**Comment by VictorLiubchenko** [comment] 2017-01-26 08:02
@giomfo Yes, @olumby is right, I'm trying use MatrixKit on Swift.

**Comment by FranciscoPereira** [comment] 2017-02-09 16:06
Same problem here.

**Comment by aapierce0** [comment] 2017-02-23 16:50
I think I can shed some light on this.

The issue is that one of MatrixKit's dependencies, GHMarkdownParser, won't build as a Dynamic Framework. Obj-C gets around this by allowing the pod to be built as a Static Library instead of a Dynamic Framework. Swift projects do not support Static Libraries, and therefore must include the `use_frameworks!` flag in the podfile.

The reason the GHMarkdownParser pod won't build as a Dynamic Framework is because it defines a type (`MMIOT`) in two different places. This is (surprisingly) allowed in Static Libraries, but not Dynamic Frameworks.

@giomfo : I created a sample Obj-C project that illustrates this error. When you uncomment the `use_frameworks!` setting in the podfile, the project won't compile, and it will generate the error above. https://github.com/aapierce0/MatrixKitClientTest

The only practical solution to this would be for MatrixKit to switch to another Markdown parsing pod. As far as I can tell, the markdown parser is only used by one class, so it wouldn't be too much work to switch it out with something else.

I can submit a pull request for this sometime this weekend.

**Comment by manuroe** [comment] 2017-02-23 17:17
*commonmark* will be an excellent replacement.
It is already used in Riot-web, not yet in Riot-iOS but we planned to do it (https://github.com/vector-im/riot-ios/issues/862).

**Comment by manuroe** [comment] 2017-02-27 16:09
Should be fixed by @aapierce0 's PR.

**Closed by manuroe** 2017-02-27 16:09 UTC
